# Generated by Django 3.0.8 on 2020-12-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freetipsgame',
            name='away_score',
        ),
        migrations.RemoveField(
            model_name='freetipsgame',
            name='home_score',
        ),
        migrations.RemoveField(
            model_name='rolltipsgame',
            name='away_score',
        ),
        migrations.RemoveField(
            model_name='rolltipsgame',
            name='home_score',
        ),
        migrations.RemoveField(
            model_name='singlebet',
            name='away_score',
        ),
        migrations.RemoveField(
            model_name='singlebet',
            name='home_score',
        ),
        migrations.RemoveField(
            model_name='viptipsgame',
            name='away_score',
        ),
        migrations.RemoveField(
            model_name='viptipsgame',
            name='home_score',
        ),
    ]
